import datetime
import importlib.metadata
import io
import json
import logging
import os
import platform
import re
import sys
import urllib.parse
import zipfile
from pathlib import Path

from jupyter_server.base.handlers import APIHandler
from jupyter_server.utils import url_path_join
from tornado import web
from tornado.httpclient import AsyncHTTPClient

# The scan itself lives in baseline.py, which the image build also runs
# on its own to record what it ships. Both sides must see a package the
# same way, so there is one implementation, imported here.
from .baseline import (
    _normalise_name,
    _path_mtime,
    _utc_now,
    read_baseline,
    scan_packages,
)

log = logging.getLogger(__name__)

MATOMO_URL = "https://matomo.icos-cp.eu/matomo.php"
MATOMO_SITE_ID = "10"

# Dependency files reported by the freeze endpoint, besides the
# "requirements*.txt" pattern handled in _is_requirement_file.
REQUIREMENT_FILENAMES = frozenset({
    "environment.yml",
    "environment.yaml",
    "Pipfile",
    "pyproject.toml",
})

# The generated Dockerfile: the name it is written under, the header
# that marks it as ours, and the one line that differs between two
# freezes of the same environment. The header marks every file the
# freeze generates, not only the Dockerfile, so one check answers "is
# this ours to overwrite?" for all of them.
DOCKERFILE_NAME = "Dockerfile"
DOCKERFILE_HEADER = "# Generated by ICOS Freeze."
FROZEN_COMMENT_PREFIX = "# Frozen:"

# The _write_generated outcomes that mean a generated file is on
# disk: it was just written, or it was already there with the same
# content. The other two, "skipped_foreign" and "error", leave no
# generated file behind, so nothing may be built or packaged from
# them.
DOCKERFILE_ON_DISK = frozenset({"written", "unchanged"})

# The rest of the build context written beside the Dockerfile: the
# exclusion list docker build reads, and the record of what was frozen.
DOCKERIGNORE_NAME = ".dockerignore"
MANIFEST_NAME = "icos-freeze.json"

# Deliberately short. The frozen directory is the build context, so
# everything not listed here is copied into the image; these are the
# entries that would either bloat it or carry state that means nothing
# inside it. What is left is the work itself: the notebooks and the
# dependency files they need, and nothing else.
#
# "*.zip" is there because the bundle endpoint leaves its handover
# package in the frozen directory, which is also the build context:
# without the entry every package would be baked into the next image,
# and the one after that would carry both.
#
# The last five are the build scaffolding and the paperwork. The
# Dockerfile, this exclusion list and the compose file describe how the
# image is built and run, so they mean nothing to a process inside it.
# The manifest and the README are the tester's, not the container's:
# the image holds the work, while the package holds the instructions
# and the record of what was frozen.
DOCKERIGNORE_ENTRIES = (
    ".ipynb_checkpoints/",
    ".git/",
    "__pycache__/",
    "*.pyc",
    ".venv/",
    "node_modules/",
    ".DS_Store",
    "*.zip",
    "Dockerfile",
    ".dockerignore",
    "docker-compose.yml",
    "icos-freeze.json",
    "README.md",
)

# The handover package: the files it generates beside the build
# context. The compose file is a package member only — nothing writes
# it into the frozen directory, which is the build context the image is
# built from.
BUNDLE_README_NAME = "README.md"
BUNDLE_COMPOSE_NAME = "docker-compose.yml"

# The token the compose file fixes for the lab service. A frozen
# environment is handed to one person to check, not published, so a
# token that can be written into the README costs nothing worth
# keeping and saves the tester a trip to the container log.
BUNDLE_COMPOSE_TOKEN = "frozen"

# The host port the compose file publishes the lab on. Not 8888: the
# person freezing is already running JupyterLab on that port, so the
# frozen copy has to land somewhere else — otherwise the container
# cannot bind. The container side stays 8888.
BUNDLE_COMPOSE_PORT = 8899

# Everything a generated slug may not contain. Runs of it collapse to a
# single underscore, so a directory name arrives as snake case and the
# package name and the tag built from it are snake case throughout.
TAG_SLUG_RE = re.compile(r"[^a-z0-9]+")

# The file conda writes beside its records; see _scan_environment.
CONDA_HISTORY_NAME = "history"

# Packages the image's own build layer installs, which no generated
# Dockerfile may pin. "icos-ext" is this extension: a frozen environment
# describes the notebooks' dependencies, never the tool that froze it.
# The rest are the build toolchain the repository Dockerfile installs
# before building the extension, plus the dependencies hatchling pulls
# in with it. They land in a pip layer that runs after the base image's
# conda packages, so the timestamp heuristic cannot help but read them
# as user installs; the baseline classifies them correctly, and this
# list keeps them out under either method.
EXCLUDED_FROM_DOCKERFILE = frozenset({
    "icos-ext",
    "hatchling",
    "hatch-nodejs-version",
    "hatch-jupyter-builder",
    "pathspec",
    "tomlkit",
    "trove-classifiers",
    "editables",
})

# Dating the base image
# ---------------------
# Everything the base image ships was linked into the environment while
# the image was being built, so it carries mtimes from the build. A
# package the user installs later is written while the container is
# already running, and because the image is pinned by digest — already
# built, already published — that is always long afterwards.
#
# The anchor is the END of the densest run of package timestamps. Sort
# every timestamp, start at the median (the image ships far more
# packages than any user adds, so the median is certain to land inside
# the build) and walk forward while consecutive packages are less than
# IMAGE_BUILD_GAP_SECONDS apart. The newest timestamp reached is when
# the image finished installing. The gap is generous because separate
# RUN layers of one image build can be minutes apart, while the gap
# between the build and anything installed at runtime is at least the
# age of the image.
#
# conda-meta/history is deliberately not the primary anchor, obvious
# though it looks: an environment laid down by a constructor installer
# ships a pre-baked history file whose mtime predates every record by
# weeks (measured on a miniforge3 prefix: history 2026-03-22, every
# record 2026-03-31). Dating the build from it would make the whole
# base image look user-installed. It is only a fallback for when there
# are no package timestamps to cluster at all.
IMAGE_BUILD_GAP_SECONDS = 60 * 60

# Slack on top of the anchor, so packages written a little after the
# last clustered one — a trailing step of the same build layer — are
# still counted as part of the image.
IMAGE_BUILD_TOLERANCE_SECONDS = 5 * 60

# Never read more than this from a single dependency file or notebook.
MAX_FILE_BYTES = 1024 * 1024

# Install magics we understand, e.g. "%pip install -q pandas==1.2.3" or
# "!pip install numpy". The reported source is "pip" or "conda".
INSTALL_RE = re.compile(
    r"^\s*[%!]\s*(?P<tool>pip3?|conda|mamba)\s+install\s+(?P<args>.+)$"
)

# Install flags that swallow the token after them, so that value is not
# mistaken for a package name. Flags written as "--flag=value" need no
# entry here: they are dropped by the leading-dash check.
INSTALL_FLAGS_WITH_VALUE = frozenset({
    "-c",
    "--channel",
    "-i",
    "--index-url",
    "--extra-index-url",
    "-f",
    "--find-links",
    "-r",
    "--requirement",
    "-t",
    "--target",
    "--prefix",
    "-n",
    "--name",
})

IMPORT_RE = re.compile(r"^import\s+(?P<modules>[^#]+)")
FROM_IMPORT_RE = re.compile(r"^from\s+(?P<module>[A-Za-z_][\w.]*)\s+import\s")

# A requirement such as "pandas[extra]==1.2.3": the name, then whatever
# version specifier follows it.
PIN_RE = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)\s*(?:\[[^\]]*\])?\s*(?P<spec>.*)$"
)

# Available from Python 3.10 on. On older runtimes the set is empty,
# which only means standard-library imports are reported instead of
# skipped.
STDLIB_MODULES = frozenset(getattr(sys, "stdlib_module_names", ()))


def _is_requirement_file(name):
    """Return True when *name* is a dependency file we report."""
    if name in REQUIREMENT_FILENAMES:
        return True
    return name.startswith("requirements") and name.endswith(".txt")


def _is_notebook_file(name):
    """Return True when *name* looks like a Jupyter notebook."""
    return name.endswith(".ipynb")


def _is_excluded(name):
    """Return True when *name* is one the freeze never reports as the user's.

    See EXCLUDED_FROM_DOCKERFILE: these come from the image's own build
    layer. They are filtered in one place for the generated Dockerfile
    and in another for the list the frontend renders, and the two must
    not drift apart — a dialog naming seven packages beside a Dockerfile
    installing none of them is worse than either view alone.
    """
    return _normalise_name(name) in EXCLUDED_FROM_DOCKERFILE


def _server_root_dir(settings):
    """Return the absolute directory the Jupyter server may serve from."""
    root = getattr(settings.get("contents_manager"), "root_dir", None)
    if not root:
        root = getattr(settings.get("serverapp"), "root_dir", None)
    return Path(root or os.getcwd()).resolve()


def _resolve_within_root(root, path):
    """Resolve *path* under *root*; return None when it escapes *root*.

    Leading and trailing slashes are stripped first, the way
    jupyter_server treats API paths, so the result can only leave the
    root through "..", a symlink, or a drive change — all of which the
    containment check below rejects.
    """
    parts = [part for part in path.strip("/").split("/") if part]
    resolved = root.joinpath(*parts).resolve()
    try:
        resolved.relative_to(root)
    except ValueError:
        return None
    return resolved


def _read_capped_text(file_path):
    """Return the capped UTF-8 text of *file_path*, or None if unreadable."""
    try:
        with open(file_path, "rb") as handle:
            raw = handle.read(MAX_FILE_BYTES + 1)
    except OSError as e:
        log.warning("Freeze: cannot read %s: %s", file_path.name, e)
        return None

    if len(raw) > MAX_FILE_BYTES:
        log.warning(
            "Freeze: truncating %s at %d bytes",
            file_path.name,
            MAX_FILE_BYTES,
        )
        raw = raw[:MAX_FILE_BYTES]

    return raw.decode("utf-8", errors="replace")


def _safe_files(directory, root, matches):
    """Return files directly in *directory* whose name passes *matches*.

    The listing is not recursive and is sorted by name. Entries that are
    not regular files, or whose symlink target lies outside *root*, are
    skipped.
    """
    try:
        with os.scandir(directory) as entries:
            candidates = sorted(
                (entry for entry in entries if matches(entry.name)),
                key=lambda entry: entry.name,
            )
    except OSError as e:
        log.warning("Freeze: cannot list directory: %s", e)
        return []

    found = []
    for entry in candidates:
        file_path = Path(entry.path)
        try:
            # Follows symlinks: broken links, directories and other
            # non-regular files all fall out here.
            if not file_path.is_file():
                continue
            target = file_path.resolve()
        except OSError as e:
            log.warning("Freeze: cannot stat %s: %s", entry.name, e)
            continue

        try:
            target.relative_to(root)
        except ValueError:
            log.warning(
                "Freeze: skipping %s, it links outside the root",
                entry.name,
            )
            continue

        found.append(file_path)

    return found


def _collect_requirements(directory, root):
    """Return dependency files directly in *directory*, sorted by name."""
    found = []
    for file_path in _safe_files(directory, root, _is_requirement_file):
        content = _read_capped_text(file_path)
        if content is None:
            continue
        found.append({"name": file_path.name, "content": content})
    return found


def _split_pin(token):
    """Return (name, version) for a requirement *token*.

    The version is only filled in for an exact "==" pin; every other
    specifier, and a bare package name, yields None.
    """
    match = PIN_RE.match(token)
    if match is None:
        return None, None

    spec = match.group("spec").strip()
    if not spec.startswith("=="):
        return match.group("name"), None

    # Keep only the first clause of e.g. "==1.2.3,!=1.2.4".
    version = spec[2:].split(",", 1)[0].strip()
    return match.group("name"), version or None


def _parse_install_line(line):
    """Return the packages pinned by an install magic, or an empty list.

    Handles several packages on one line and drops flags such as "-q",
    "--upgrade" or "--index-url <url>".
    """
    match = INSTALL_RE.match(line)
    if match is None:
        return []

    source = "conda" if match.group("tool") in ("conda", "mamba") else "pip"
    args = match.group("args").split("#", 1)[0]

    packages = []
    skip_next = False
    for token in args.split():
        if skip_next:
            skip_next = False
            continue
        if token.startswith("-"):
            skip_next = token in INSTALL_FLAGS_WITH_VALUE
            continue

        token = token.strip("\"'").split(";", 1)[0].strip()
        if not token:
            continue

        name, version = _split_pin(token)
        if name is None:
            continue
        packages.append({"name": name, "version": version, "source": source})

    return packages


def _parse_import_line(line):
    """Return the root modules imported by a top-level import *line*.

    Standard-library modules are left out, and only the root of a dotted
    module path is reported.
    """
    if line[:1].isspace():
        return []

    modules = []
    from_match = FROM_IMPORT_RE.match(line)
    if from_match is not None:
        modules.append(from_match.group("module"))
    else:
        import_match = IMPORT_RE.match(line)
        if import_match is None:
            return []
        for part in import_match.group("modules").split(","):
            name = part.strip().split(" as ", 1)[0].strip()
            if name:
                modules.append(name)

    roots = []
    for module in modules:
        root = module.split(".", 1)[0]
        if not root.isidentifier() or root in STDLIB_MODULES:
            continue
        roots.append({"name": root, "version": None, "source": "import"})

    return roots


def _code_cell_lines(cell):
    """Return the source lines of *cell* when it is a code cell."""
    if not isinstance(cell, dict) or cell.get("cell_type") != "code":
        return []

    source = cell.get("source", "")
    if isinstance(source, list):
        source = "".join(part for part in source if isinstance(part, str))
    if not isinstance(source, str):
        return []

    return source.splitlines()


def _notebook_packages(file_path):
    """Return the packages named in *file_path*, or None if unreadable.

    Packages keep the spelling used in the notebook and the order they
    are first seen in. A pinned install replaces an earlier versionless
    mention of the same package, keeping that first position.
    """
    text = _read_capped_text(file_path)
    if text is None:
        return None

    try:
        document = json.loads(text)
    except ValueError as e:
        log.warning("Freeze: cannot parse %s: %s", file_path.name, e)
        return None

    if not isinstance(document, dict) or not isinstance(document.get("cells"), list):
        log.warning("Freeze: %s is not a notebook, skipping", file_path.name)
        return None

    packages = {}
    for cell in document["cells"]:
        for line in _code_cell_lines(cell):
            found = _parse_install_line(line) or _parse_import_line(line)
            for package in found:
                key = _normalise_name(package["name"])
                known = packages.get(key)
                if known is None:
                    packages[key] = package
                elif known["version"] is None and package["version"]:
                    known.update(package)

    return list(packages.values())


def _collect_notebooks(directory, root):
    """Return the packages of every notebook directly in *directory*."""
    notebooks = []
    for file_path in _safe_files(directory, root, _is_notebook_file):
        packages = _notebook_packages(file_path)
        if packages is None:
            continue
        notebooks.append({"name": file_path.name, "packages": packages})
    return notebooks


def _parse_requirement_pins(content):
    """Return {normalised name: version} for the "==" pins in *content*.

    Comments, blank lines, "-r" includes and anything that is not an
    exact pin are ignored. The first pin for a package wins.
    """
    pins = {}
    for raw_line in content.splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue

        if line.startswith("-"):
            # "-r other.txt", "-e ." and "--index-url ..." are not pins,
            # while a leading "- " is a YAML list item in an
            # environment.yml dependency list.
            if not line.startswith("- "):
                continue
            line = line[2:].strip()

        # Tolerate the quoting and commas used in pyproject.toml and
        # environment.yml dependency lists.
        line = line.strip(",").strip("\"'").strip()
        line = line.split(";", 1)[0].strip()
        if not line:
            continue

        name, version = _split_pin(line)
        if version is None:
            continue
        pins.setdefault(_normalise_name(name), version)

    return pins


def _find_conflicts(notebooks, requirements):
    """Return every package pinned to different versions in two places.

    A package only conflicts when both the notebook and a dependency
    file pin it exactly, so a plain import never conflicts.
    """
    pinned_files = [
        (item["name"], _parse_requirement_pins(item["content"]))
        for item in requirements
    ]

    conflicts = []
    for notebook in notebooks:
        for package in notebook["packages"]:
            if not package["version"]:
                continue
            key = _normalise_name(package["name"])
            for file_name, pins in pinned_files:
                pinned = pins.get(key)
                if pinned is None or pinned == package["version"]:
                    continue
                conflicts.append({
                    "package": package["name"],
                    "notebook": notebook["name"],
                    "notebook_version": package["version"],
                    "requirements_file": file_name,
                    "requirements_version": pinned,
                })

    return conflicts


def _notebook_installs(notebooks):
    """Return the notebooks that install packages from inside a cell.

    One record per notebook that has at least one install-sourced
    package: {"name": ..., "packages": [...]}. Package names keep the
    spelling used in the notebook, are de-duplicated by normalised name
    and sorted, and the records are sorted by notebook name. An import
    is not an install and never appears here.
    """
    installs = []
    for notebook in notebooks:
        names = {}
        for package in notebook["packages"]:
            if package["source"] not in ("pip", "conda"):
                continue
            names.setdefault(_normalise_name(package["name"]), package["name"])
        if not names:
            continue
        installs.append({
            "name": notebook["name"],
            "packages": [names[key] for key in sorted(names)],
        })

    return sorted(installs, key=lambda entry: entry["name"])


def _better_import_name(current, candidate, key):
    """Return True when *candidate* is the better import name for *key*."""
    if current is None:
        return True
    if _normalise_name(candidate) == key:
        return True
    if _normalise_name(current) == key:
        return False
    # A private helper module such as "_distutils_hack" is never what a
    # notebook imports.
    if current.startswith("_") != candidate.startswith("_"):
        return current.startswith("_")
    return candidate < current


def _import_maps():
    """Return (import name -> distributions, normalised name -> import name).

    Both come from importlib.metadata.packages_distributions(), which is
    how "sklearn" resolves to "scikit-learn" and "PIL" to "pillow". It
    is new in Python 3.10; on an older runtime the maps come back empty
    and package names are simply reported as written.
    """
    packages_distributions = getattr(
        importlib.metadata, "packages_distributions", None
    )
    if packages_distributions is None:
        log.warning("Freeze: this runtime cannot map import names")
        return {}, {}

    try:
        mapping = packages_distributions()
    except Exception as e:
        log.warning("Freeze: cannot map import names: %s", e)
        return {}, {}

    import_names = {}
    for import_name, dist_names in mapping.items():
        for dist_name in dist_names:
            key = _normalise_name(dist_name)
            if _better_import_name(import_names.get(key), import_name, key):
                import_names[key] = import_name

    return mapping, import_names


def _image_build_time(timestamps):
    """Return when the base image finished installing packages.

    See "Dating the base image" above for why the end of the densest run
    of timestamps is the anchor. Returns None when there is nothing to
    cluster.
    """
    ordered = sorted(stamp for stamp in timestamps if stamp is not None)
    if not ordered:
        return None

    index = len(ordered) // 2
    while index + 1 < len(ordered):
        if ordered[index + 1] - ordered[index] > IMAGE_BUILD_GAP_SECONDS:
            break
        index += 1

    return ordered[index]


def _provenance(timestamp, build_time):
    """Return "user", "image" or "unknown" for one installed package.

    "unknown" is not a guess dressed up as an answer: it is what we
    report whenever a timestamp is missing, so the caller can say the
    heuristic did not apply instead of pretending it did.
    """
    if timestamp is None or build_time is None:
        return "unknown"
    if timestamp > build_time + IMAGE_BUILD_TOLERANCE_SECONDS:
        return "user"
    return "image"


def _baseline_provenance(key, version, baseline_packages):
    """Return "user" or "image" for one package, against the baseline.

    A package the image did not ship is the user's. So is one the image
    shipped at another version, because the user must have upgraded or
    downgraded it and the rebuilt image has to do the same. Nothing here
    is a guess, so "unknown" never comes out of this path.
    """
    recorded = baseline_packages.get(key)
    if recorded is None:
        return "user"
    if recorded.get("version") != version:
        return "user"
    return "image"


def _timestamp_provenances(packages, conda_meta, timestamps):
    """Return {key: provenance} from the mtime heuristic.

    The fallback for an image built before baselines existed. See
    "Dating the base image" above for what it can and cannot tell.
    """
    build_time = _image_build_time(timestamps)
    if build_time is None:
        build_time = _path_mtime(conda_meta / CONDA_HISTORY_NAME)
    if build_time is None:
        log.warning(
            "Freeze: cannot date the base image, every package will be "
            "reported with unknown provenance"
        )

    return {
        key: _provenance(package["mtime"], build_time)
        for key, package in packages.items()
    }


def _scan_environment():
    """Return a snapshot of the packages installed in the running server.

    The scan walks conda-meta/ and every ".dist-info" directory, so it
    is taken once per request and passed down rather than repeated for
    each package looked up.

    Provenance — who installed a package, the image or the user — is
    read off the baseline the image build recorded, which is exact. Only
    when there is no usable baseline does it fall back to the timestamp
    heuristic, and "provenance_method" says which of the two answered,
    because the timestamps cannot tell a late image-build layer from a
    runtime install and the baseline can.
    """
    scan = scan_packages()
    packages = scan["packages"]
    import_map, import_names = _import_maps()

    baseline = read_baseline()
    if baseline is None:
        method = "timestamps"
        provenances = _timestamp_provenances(
            packages, scan["conda_meta"], scan["timestamps"]
        )
    else:
        method = "baseline"
        recorded = baseline["packages"]
        provenances = {
            key: _baseline_provenance(key, package["version"], recorded)
            for key, package in packages.items()
        }

    return {
        "python_version": platform.python_version(),
        "provenance_method": method,
        "packages": {
            key: {
                "name": package["name"],
                "version": package["version"],
                "manager": package["manager"],
                "provenance": provenances[key],
            }
            for key, package in packages.items()
        },
        "import_map": import_map,
        "import_names": import_names,
    }


def _resolve_package(token, environment):
    """Return the environment entry for the package spelled *token*.

    *token* is whatever the notebook said: an import name such as
    "sklearn", or the distribution name an install magic used. Import
    names are resolved first, so both spellings land on one entry.
    """
    import_name = None
    dist_name = token

    candidates = environment["import_map"].get(token)
    if candidates:
        import_name = token
        dist_name = sorted(candidates)[0]

    key = _normalise_name(dist_name)
    if import_name is None:
        import_name = environment["import_names"].get(key)

    installed = environment["packages"].get(key)
    if installed is None:
        return {
            "name": dist_name,
            "import_name": import_name,
            "installed_version": None,
            "manager": None,
            "provenance": "unknown",
        }

    return {
        "name": installed["name"],
        "import_name": import_name,
        "installed_version": installed["version"],
        "manager": installed["manager"],
        "provenance": installed["provenance"],
    }


def _resolve_environment(notebooks, environment):
    """Return (entries, missing) for the packages the notebooks name.

    *entries* holds one record per distinct package, sorted by
    normalised name; *missing* names the ones the running environment
    does not have at all, which is a hole no generated Dockerfile can
    fill.
    """
    entries = {}
    for notebook in notebooks:
        if not isinstance(notebook, dict):
            continue
        for package in notebook.get("packages") or []:
            if not isinstance(package, dict):
                continue
            token = package.get("name")
            if not isinstance(token, str) or not token:
                continue
            entry = _resolve_package(token, environment)
            entries.setdefault(_normalise_name(entry["name"]), entry)

    resolved = [entries[key] for key in sorted(entries)]
    missing = [
        entry["name"]
        for entry in resolved
        if entry["installed_version"] is None
    ]
    return resolved, missing


def _user_installed(environment):
    """Return every package installed on top of the base image.

    This is the whole user-installed set, not just the part the
    notebooks happen to name: a package imported from a helper module
    beside the notebooks, or pulled in as a pinned dependency of one the
    notebooks do name, is just as much part of the environment being
    frozen. Leaving it out would mean the rebuilt image resolves it
    differently, or not at all.

    Packages from the image's own build layer are left out, the same
    ones the generated Dockerfile refuses to pin, so the two views agree
    on what was installed on top of the image. The notebook-referenced
    view is not filtered this way: a notebook that genuinely imports one
    of those names should still say so.

    Entries carry the same fields as the notebook-referenced view, so
    the frontend can render either list the same way, and are sorted by
    normalised name.
    """
    found = [
        {
            "name": package["name"],
            "import_name": environment["import_names"].get(key),
            "installed_version": package["version"],
            "manager": package["manager"],
            "provenance": "user",
        }
        for key, package in environment["packages"].items()
        if package["provenance"] == "user" and not _is_excluded(package["name"])
    ]
    return sorted(found, key=lambda entry: _normalise_name(entry["name"]))


def _session_image():
    """Return the image this session runs on, or None when unknown.

    Set by JupyterHub on the real deployment; absent locally unless
    docker-compose.yml provides it. No fallback guess.
    """
    return os.environ.get("JUPYTER_IMAGE_SPEC") or None


def _join_names(names):
    """Return *names* as "a", "a and b", or "a, b and c"."""
    if len(names) < 3:
        return " and ".join(names)
    return f"{', '.join(names[:-1])} and {names[-1]}"


def _dockerfile_block_reason(image, conflicts, installs):
    """Return why no Dockerfile can be written, or None when one can.

    Conflicts are reported first: an unknown image is beside the point
    while the pins still disagree. Installs run from inside a notebook
    come next — they leave the environment unreproducible from the
    image and the requirement files, which is what a freeze promises.
    The unknown image is last.

    At most three notebooks are named, so the reason stays short enough
    to show in the frontend.
    """
    if conflicts:
        count = len(conflicts)
        plural = "" if count == 1 else "s"
        return (
            f"Resolve the {count} version conflict{plural} in your files, "
            "then freeze again."
        )

    if installs:
        named = installs[:3]
        clauses = [
            f"{entry['name']} installs {_join_names(entry['packages'])}"
            for entry in named
        ]
        noun = "notebook" if len(installs) == 1 else "notebooks"
        lead = f"{'; '.join(clauses)} from inside the {noun}"
        rest = len(installs) - len(named)
        if rest:
            verb = "does" if rest == 1 else "do"
            lead += f", and {rest} more {verb} the same"
        return (
            f"{lead}, so this environment cannot be rebuilt from the "
            "image and the requirement files alone. Move those packages "
            "into requirements.txt, install them, then freeze again."
        )

    if not image:
        return (
            "The server did not report a JUPYTER_IMAGE_SPEC, so the base "
            "image is unknown."
        )

    return None


def _dockerfile_write_reason(outcome):
    """Return why the generated Dockerfile is not on disk.

    Only called for a write outcome outside DOCKERFILE_ON_DISK, so
    there is always something to say.
    """
    if outcome == "skipped_foreign":
        return (
            "This directory already has a Dockerfile that ICOS Freeze "
            "did not write, so it was left alone. Move or rename it, "
            "then freeze again."
        )

    return (
        "The Dockerfile could not be written to this directory, so "
        "there is nothing to build or package. Check that you can "
        "write to the directory, then freeze again."
    )


def _run_install_lines(command, specs, tail=None):
    """Return the RUN lines installing *specs* with *command*.

    A single package stays on one line; several are spread over
    backslash-continued lines, the way the repository's own Dockerfile
    formats a long RUN.
    """
    if len(specs) == 1:
        line = f"RUN {command} {specs[0]}"
        return [f"{line} && {tail}" if tail else line]

    lines = [f"RUN {command} \\"]
    for index, spec in enumerate(specs):
        if index < len(specs) - 1:
            lines.append(f"      {spec} \\")
        elif tail:
            lines.append(f"      {spec} && \\")
            lines.append(f"      {tail}")
        else:
            lines.append(f"      {spec}")

    return lines


def _pinnable(entry):
    """Return (name, version) for *entry*, or None when it cannot be pinned.

    Entries that do not look the way the scan produces them are skipped
    rather than raising: the Dockerfile is a starting point, not a
    contract.
    """
    if not isinstance(entry, dict):
        return None

    name = entry.get("name")
    version = entry.get("installed_version")
    if not isinstance(name, str) or not name:
        return None
    if not isinstance(version, str) or not version:
        return None

    return name, version


def _dockerfile_groups(environment, user_installed):
    """Return the packages each Dockerfile section installs or mentions.

    "conda" and "pip" come from *user_installed*: every package put on
    top of the base image gets a RUN line, whether or not a notebook
    names it, because all of it is part of the environment being frozen.

    "unknown" comes from *environment*, the notebook-referenced view.
    Scoping it that way is deliberate: when the scan cannot date the
    image at all, every installed package has unknown provenance, and
    listing the notebooks' handful is useful where listing the whole of
    site-packages would not be. Unknown provenance never becomes a RUN
    line either way.

    Packages in EXCLUDED_FROM_DOCKERFILE are dropped from every section,
    whichever method decided their provenance.

    Every list is sorted by normalised name and de-duplicated, so the
    same environment always produces the same file.
    """
    groups = {"conda": [], "pip": [], "unknown": []}

    for entry in user_installed or []:
        pin = _pinnable(entry)
        if pin is None or entry.get("provenance") != "user":
            continue
        if _is_excluded(pin[0]):
            continue
        manager = entry.get("manager")
        if manager in ("conda", "pip"):
            groups[manager].append(pin)

    for entry in environment or []:
        pin = _pinnable(entry)
        if pin is None or entry.get("provenance") != "unknown":
            continue
        if _is_excluded(pin[0]):
            continue
        groups["unknown"].append(pin)

    return {
        section: sorted(set(found), key=lambda pin: _normalise_name(pin[0]))
        for section, found in groups.items()
    }


def _provenance_comments(method):
    """Return the header lines saying how provenance was decided."""
    if method == "baseline":
        return [
            "# Provenance: the package baseline recorded when the image"
            " was built,",
            "# so the list below is exactly what was installed on top of"
            " it.",
        ]

    return [
        "# Provenance: file timestamps — no package baseline was found"
        " in this",
        "# image. Timestamps cannot tell a late layer of the image's own"
        " build from",
        "# a package you installed, so the list below may include some"
        " the image",
        "# already ships. Review it before rebuilding.",
    ]


def _generate_dockerfile(
    path,
    image,
    environment,
    user_installed,
    missing,
    python_version,
    provenance_method,
):
    """Return the text of a Dockerfile rebuilding the frozen environment.

    The base image is pinned by digest, so everything it ships is
    already reproduced exactly and must not be pinned a second time.
    Every package installed on top of it is listed, with the manager
    that owns it: pip-installing a conda-managed package resolves to a
    different environment, which is the failure this file exists to
    prevent.

    *user_installed* drives the RUN lines and *environment* only the
    comment blocks, so a package the notebooks never name still gets
    rebuilt.

    *provenance_method* is "baseline" or "timestamps" and is written
    into the header: a reader has to know whether the list is exact or a
    best guess before trusting it.

    Apart from the "# Frozen:" stamp the output depends only on the
    arguments, so freezing the same environment twice gives the same
    file.
    """
    groups = _dockerfile_groups(environment, user_installed)

    lines = [
        DOCKERFILE_HEADER,
        f"# Directory: {path or '/'}",
        f"{FROZEN_COMMENT_PREFIX} {_utc_now()}",
        f"# Python: {python_version or 'unknown'}",
        "#",
        "# The base image is pinned by digest, so everything it ships is"
        " already",
        "# reproduced exactly. Only packages installed on top of it are"
        " listed below.",
        "#",
    ]
    lines.extend(_provenance_comments(provenance_method))
    lines.extend(["", f"FROM {image}"])

    conda = groups["conda"]
    if conda:
        lines.append("")
        lines.append("# Installed with conda on top of the base image.")
        lines.extend(_run_install_lines(
            "mamba install -y -q",
            [f"{name}=={version}" for name, version in conda],
            tail="mamba clean -afy",
        ))

    pip = groups["pip"]
    if pip:
        lines.append("")
        lines.append("# Installed with pip on top of the base image.")
        lines.extend(_run_install_lines(
            "pip install --no-cache-dir",
            [f"{name}=={version}" for name, version in pip],
        ))

    if not conda and not pip:
        lines.extend([
            "",
            "# Nothing was installed on top of the base image, so the"
            " digest",
            "# above reproduces this environment on its own.",
        ])

    names = sorted(
        {name for name in (missing or []) if isinstance(name, str) and name},
        key=_normalise_name,
    )
    if names:
        lines.extend([
            "",
            "# Referenced by the notebooks but not installed in the"
            " frozen",
            "# environment, so this build cannot reproduce them:",
        ])
        lines.extend(f"#   {name}" for name in names)

    unknown = groups["unknown"]
    if unknown:
        lines.extend([
            "",
            "# Provenance could not be determined for these; they may"
            " already be in",
            "# the base image:",
        ])
        lines.extend(f"#   {name}=={version}" for name, version in unknown)

    lines.append("")
    lines.append("WORKDIR /home/jovyan/work")
    lines.extend([
        "",
        "# The frozen directory is the build context, so the notebooks"
        " and their",
        "# dependency files are baked into the image instead of having"
        " to be mounted",
        "# beside it. 1000:100 is NB_UID:NB_GID in the base image, so"
        " the copied",
        "# files belong to jovyan.",
        "COPY --chown=1000:100 . /home/jovyan/work",
    ])

    return "\n".join(lines) + "\n"


def _dockerfile_body(content):
    """Return *content* without its "# Frozen:" stamp.

    Two freezes of an unchanged environment differ in that one line and
    nothing else, so the check that decides whether the file on disk
    still matches leaves it out.
    """
    return "\n".join(
        line
        for line in content.splitlines()
        if not line.startswith(FROZEN_COMMENT_PREFIX)
    )


def _write_generated(directory, name, content, compare=None):
    """Write a generated file into *directory*; return what happened.

    One of "written", "unchanged", "skipped_foreign" or "error". A file
    that does not carry DOCKERFILE_HEADER was written by someone else
    and is left where it is, so a hand-written one is never clobbered,
    and identical content is not rewritten.

    *compare* normalises both sides before they are compared, for the
    lines that differ between two freezes of one environment; without it
    the texts are compared as they are.

    The Dockerfile and the .dockerignore share this because they share
    every rule about when a file on disk may be replaced, and two copies
    of those rules would be one edit away from disagreeing.
    """
    target = directory / name
    normalise = compare or (lambda text: text)

    try:
        existing = target.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = None
    except (OSError, ValueError) as e:
        log.warning("Freeze: cannot read the existing %s: %s", name, e)
        return "error"

    if existing is not None:
        if not existing.startswith(DOCKERFILE_HEADER):
            log.warning(
                "Freeze: %s was not generated by ICOS Freeze, leaving it alone",
                name,
            )
            return "skipped_foreign"
        if normalise(existing) == normalise(content):
            return "unchanged"

    try:
        target.write_text(content, encoding="utf-8")
    except OSError as e:
        log.warning("Freeze: cannot write %s: %s", name, e)
        return "error"

    return "written"


def _write_dockerfile(directory, content):
    """Write the generated Dockerfile into *directory*; return what happened.

    See _write_generated for the vocabulary. The "# Frozen:" stamp is
    left out of the comparison, so an unchanged environment does not
    rewrite the file just because time has passed.
    """
    return _write_generated(
        directory,
        DOCKERFILE_NAME,
        content,
        compare=_dockerfile_body,
    )


def _generate_dockerignore():
    """Return the text of the .dockerignore for a frozen directory.

    It depends on nothing but DOCKERIGNORE_ENTRIES, so a second freeze
    of any directory produces the same file and rewrites nothing.
    """
    lines = [
        DOCKERFILE_HEADER,
        "# The frozen directory is the build context. These entries are"
        " checkout",
        "# state, caches, handover packages and the build scaffolding"
        " itself — the",
        "# Dockerfile, this file and the compose file describe how the"
        " image is",
        "# built and run, so none of them belongs inside it.",
        "#",
        f"# The freeze manifest {MANIFEST_NAME} and the README are"
        " excluded for the",
        "# same reason: the image holds the work, while the package"
        " holds the",
        "# instructions and the record of what was frozen.",
        "",
    ]
    lines.extend(DOCKERIGNORE_ENTRIES)
    return "\n".join(lines) + "\n"


def _write_dockerignore(directory):
    """Write the generated .dockerignore into *directory*.

    Same vocabulary and same foreign-file guard as the Dockerfile: a
    .dockerignore the user wrote is theirs, and silently replacing it
    would change what a later build ships without saying so.
    """
    return _write_generated(
        directory,
        DOCKERIGNORE_NAME,
        _generate_dockerignore(),
    )


def _manifest_document(image, snapshot):
    """Return the freeze manifest for *snapshot*, ready to serialise.

    It records what the directory was frozen from — the base image, the
    Python version, how provenance was decided, and the files and
    packages involved — so a rebuilt image can be traced back without
    anyone having to read the Dockerfile and guess.

    "pid" is a placeholder for a future persistent identifier: the
    handle that will be minted for a frozen environment so it can be
    cited. It is always null for now, and is in schema 1 so a reader can
    look the field up rather than have it appear under them later.
    """
    return {
        "schema": 1,
        "pid": None,
        "frozen_at": _utc_now(),
        "image": image,
        "python_version": snapshot["python_version"],
        "provenance_method": snapshot["provenance_method"],
        "notebooks": [item["name"] for item in snapshot["notebooks"]],
        "requirements": [item["name"] for item in snapshot["requirements"]],
        "user_installed": [
            {
                "name": entry["name"],
                "installed_version": entry["installed_version"],
                "manager": entry["manager"],
            }
            for entry in snapshot["user_installed"]
        ],
        "missing": list(snapshot["missing"]),
    }


def _write_manifest(directory, document):
    """Write the freeze manifest into *directory*; return the outcome.

    "written" or "error". There is no foreign-file guard here: the name
    is ours by definition, and "frozen_at" changes on every freeze, so
    the file is always rewritten rather than compared.
    """
    target = directory / MANIFEST_NAME

    try:
        target.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    except OSError as e:
        log.warning("Freeze: cannot write %s: %s", MANIFEST_NAME, e)
        return "error"

    return "written"


def _write_build_context(directory, dockerfile, image, snapshot):
    """Write the whole build context into *directory*; return the outcomes.

    {"dockerfile": ..., "dockerignore": ..., "manifest": ...}, each in
    the vocabulary of _write_generated. The three files are written
    together because a directory with only some of them is not something
    docker build can be pointed at, and which endpoint the freeze came
    through should not decide what the user ends up holding.
    """
    return {
        "dockerfile": _write_dockerfile(directory, dockerfile),
        "dockerignore": _write_dockerignore(directory),
        "manifest": _write_manifest(directory, _manifest_document(image, snapshot)),
    }


def _directory_slug(directory):
    """Return *directory*'s name as a snake case slug.

    Anything outside a-z and 0-9 collapses to a single underscore, so
    "My Analysis" and "my-analysis" both arrive as "my_analysis". A name
    that survives as nothing — the server root among them — becomes
    "root". The generated tag and the generated package name are both
    built on it, so one directory is named the same way by both.
    """
    return TAG_SLUG_RE.sub("_", directory.name.lower()).strip("_") or "root"


def _utc_stamp():
    """Return the current UTC time as a compact, sortable stamp.

    ISO 8601 basic format: the T separates the date from the time and
    the Z says the time is UTC, so a stamp read on its own cannot be
    mistaken for local time. Both are legal in a Docker tag and in a
    filename on every platform we ship to.
    """
    now = datetime.datetime.now(datetime.timezone.utc)
    return now.strftime("%Y%m%dT%H%M%SZ")


def _generated_tag(directory):
    """Return the default image tag for a build of *directory*.

    "icos-frozen:<slug>_<stamp>", the slug from the directory name and
    the stamp UTC to the second. The stamp is what keeps successive
    builds of one directory apart, instead of each quietly taking the
    tag off the last.
    """
    return f"icos-frozen:{_directory_slug(directory)}_{_utc_stamp()}"


def _bundle_member_bytes(file_path):
    """Return the bytes of *file_path*, or None when it cannot be read.

    One unreadable file must not cost the whole package: the caller
    leaves it out and the README names what actually went in.
    """
    try:
        return file_path.read_bytes()
    except OSError as e:
        log.warning(
            "Freeze: cannot read %s for the package: %s", file_path.name, e
        )
        return None


def _bundle_files(directory, items):
    """Return [(name, bytes)] for the freeze *items* that can be read.

    *items* are the snapshot's notebook or dependency-file records. A
    ".zip" is never taken along: the frozen directory also holds the
    packages earlier freezes left in it, and a package inside a package
    is only weight.
    """
    found = []
    for item in items or []:
        if not isinstance(item, dict):
            continue
        name = item.get("name")
        if not isinstance(name, str) or not name or name.endswith(".zip"):
            continue
        data = _bundle_member_bytes(directory / name)
        if data is None:
            continue
        found.append((name, data))
    return found


def _bundle_manifest(data):
    """Return the manifest parsed from *data*, or an empty mapping.

    The README quotes the manifest that is in the package rather than
    values computed a second time, so the two cannot disagree about when
    the directory was frozen or from which image.
    """
    if data is None:
        return {}

    try:
        document = json.loads(data.decode("utf-8"))
    except (UnicodeDecodeError, ValueError) as e:
        log.warning("Freeze: cannot read %s for the package: %s", MANIFEST_NAME, e)
        return {}

    return document if isinstance(document, dict) else {}


def _compose_url():
    """Return the URL the compose file's lab service answers on."""
    return (
        f"http://localhost:{BUNDLE_COMPOSE_PORT}"
        f"/lab?token={BUNDLE_COMPOSE_TOKEN}"
    )


def _generate_compose(tag):
    """Return the docker-compose.yml shipped in the handover package.

    One service over the one build context: "lab" is the environment to
    work in, built from the Dockerfile beside it, so the tester builds
    once and works in exactly what was frozen.

    JUPYTER_TOKEN is fixed rather than generated: it makes the URL
    predictable enough to write into the README, instead of the tester
    having to fish a one-time token out of the container log.
    """
    return "\n".join([
        DOCKERFILE_HEADER,
        "#",
        "# Brings the frozen environment up from this directory.",
        "#",
        "#   docker compose up --build",
        f"#       JupyterLab on {_compose_url()}",
        "",
        "services:",
        "  lab:",
        "    build: .",
        f"    image: {tag}",
        "    ports:",
        f'      - "{BUNDLE_COMPOSE_PORT}:8888"',
        "    environment:",
        "      # Fixed on purpose, so the URL above is the URL every",
        "      # time; the container log does not have to be read.",
        f'      JUPYTER_TOKEN: "{BUNDLE_COMPOSE_TOKEN}"',
    ]) + "\n"


def _generate_bundle_readme(
    directory,
    tag,
    manifest,
    notebooks,
    requirements,
    missing,
):
    """Return the README shipped in the handover package.

    It is addressed to someone who has Docker and this zip and nothing
    else: no checkout, no access to the server the directory was frozen
    on, and no reason to read the Dockerfile first. Every command is
    written out with the real tag, so it can be pasted as it stands.
    """
    name = directory.name or "/"
    image = manifest.get("image") or "unknown"
    frozen_at = manifest.get("frozen_at") or "unknown"

    lines = [
        f"# Frozen environment: {name}",
        "",
        "This package holds the notebooks that were in the JupyterLab"
        f" directory `{name}`, their dependency files, and a Dockerfile"
        " that rebuilds the environment they ran in.",
        "",
        f"- Frozen at: {frozen_at}",
        f"- Base image: {image}",
        "",
        "You need Docker and this package. Unpack the zip and run the"
        " commands below from the unpacked directory.",
        "",
        "## Build and run",
        "",
        "```bash",
        "docker compose up --build",
        "```",
        "",
        f"Then open {_compose_url()}. The notebooks are at"
        " `/home/jovyan/work` inside the container. The token is fixed"
        f" in `{BUNDLE_COMPOSE_NAME}`, so that URL is the same every"
        " time.",
        "",
        "Without compose:",
        "",
        "```bash",
        f"docker build -t {tag} .",
        f"docker run --rm -p {BUNDLE_COMPOSE_PORT}:8888 {tag}",
        "```",
        "",
        "Run that way, JupyterLab prints its URL, with a one-time token"
        " in it, to the container log as it starts. That URL carries the"
        " container's own port, so open it with the host port instead:"
        f" `http://localhost:{BUNDLE_COMPOSE_PORT}/lab?token=...`.",
        "",
        "## What to check",
        "",
        "Open the notebooks in the running container and run each of"
        " them top to bottom. Nothing should have to be installed along"
        " the way: an install line such as `%pip install ...` that"
        " actually has to fetch a package means the image is missing"
        " it.",
        "",
        f"Then compare the packages `{MANIFEST_NAME}` lists under"
        " `user_installed` against what the container reports. The"
        " manifest is in this unpacked package, so read it here and run"
        " this from the same machine:",
        "",
        "```bash",
        f"docker run --rm {tag} pip list",
        "```",
        "",
        "Every package under `user_installed` should be in that list, at"
        " the version the manifest records.",
        "",
        "## What is in this package",
        "",
        f"- `{DOCKERFILE_NAME}`, `{DOCKERIGNORE_NAME}` — the build context",
        f"- `{BUNDLE_COMPOSE_NAME}` — brings the environment up with one"
        " command",
        f"- `{MANIFEST_NAME}` — what was frozen, and from which image",
        f"- Notebooks: {', '.join(notebooks) if notebooks else 'none'}",
        "- Dependency files:"
        f" {', '.join(requirements) if requirements else 'none'}",
    ]

    names = sorted(
        {item for item in (missing or []) if isinstance(item, str) and item},
        key=_normalise_name,
    )
    if names:
        lines.extend([
            "",
            "## Missing packages",
            "",
            "The notebooks reference these, but they were not installed in"
            " the frozen environment, so the build cannot reproduce them"
            " and the notebooks that use them are expected to fail:",
            "",
        ])
        lines.extend(f"- {item}" for item in names)

    return "\n".join(lines) + "\n"


def _bundle_archive(directory, snapshot, image):
    """Return (filename, bytes) for the handover package of *directory*.

    A flat zip: the build context that was just written into the
    directory, the notebooks and dependency files it describes, a README
    for whoever has to build it, and a compose file that does the build
    and the run in one command. Flat because the tester unpacks it and
    builds in the
    unpacked directory — a directory prefix would only be one more
    thing to get wrong.

    The build-context files are read back from disk rather than
    generated a second time, so the package and the directory cannot
    disagree about what was frozen. *image* is only a fallback for the
    README: the manifest on disk is the authority.
    """
    tag = _generated_tag(directory)

    context = []
    manifest_data = None
    for name in (DOCKERFILE_NAME, DOCKERIGNORE_NAME, MANIFEST_NAME):
        data = _bundle_member_bytes(directory / name)
        if data is None:
            continue
        if name == MANIFEST_NAME:
            manifest_data = data
        context.append((name, data))

    notebooks = _bundle_files(directory, snapshot["notebooks"])
    requirements = _bundle_files(directory, snapshot["requirements"])

    manifest = _bundle_manifest(manifest_data)
    if not manifest.get("image"):
        # Only reached when the manifest could not be read back; the
        # file on disk is otherwise the authority on what this is.
        manifest["image"] = image
    readme = _generate_bundle_readme(
        directory,
        tag,
        manifest,
        [name for name, _ in notebooks],
        [name for name, _ in requirements],
        snapshot["missing"],
    )
    compose = _generate_compose(tag)

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for name, data in context + notebooks + requirements:
            archive.writestr(name, data)
        archive.writestr(BUNDLE_README_NAME, readme)
        archive.writestr(BUNDLE_COMPOSE_NAME, compose)

    filename = f"{_directory_slug(directory)}_frozen_{_utc_stamp()}.zip"
    return filename, buffer.getvalue()


def _write_bundle(directory, name, data):
    """Write the handover package into *directory*; return True on success.

    The download is the primary path, so a directory that cannot be
    written to costs the copy and nothing else: the caller still has the
    bytes and says in a response header whether the copy landed.
    """
    try:
        (directory / name).write_bytes(data)
    except OSError as e:
        log.warning("Freeze: cannot write %s: %s", name, e)
        return False

    return True


def _freeze_snapshot(handler, path):
    """Return the freeze snapshot for *path*.

    The keys are "directory", "requirements", "notebooks", "conflicts",
    "notebook_installs", "environment", "user_installed", "missing",
    "python_version" and "provenance_method". It is a mapping rather
    than a tuple because "environment" and "user_installed" are both
    lists of package records, and positional unpacking is one edit away
    from silently swapping them.

    Both freeze endpoints collect the snapshot this way, so they answer
    the same 400 and 404, never differ on what a directory contains, and
    scan the live environment exactly once per request.
    """
    root = _server_root_dir(handler.settings)

    directory = _resolve_within_root(root, path)
    if directory is None:
        log.warning("Freeze: rejected path outside the root: %r", path)
        raise web.HTTPError(
            400, "Requested path is outside the server root directory"
        )
    if not directory.is_dir():
        log.warning("Freeze: directory not found: %r", path)
        raise web.HTTPError(404, "Directory not found")

    requirements = _collect_requirements(directory, root)
    notebooks = _collect_notebooks(directory, root)
    conflicts = _find_conflicts(notebooks, requirements)
    installs = _notebook_installs(notebooks)

    scan = _scan_environment()
    environment, missing = _resolve_environment(notebooks, scan)

    return {
        "directory": directory,
        "requirements": requirements,
        "notebooks": notebooks,
        "conflicts": conflicts,
        "notebook_installs": installs,
        "environment": environment,
        "user_installed": _user_installed(scan),
        "missing": missing,
        "python_version": scan["python_version"],
        "provenance_method": scan["provenance_method"],
    }


class TrackHandler(APIHandler):
    @web.authenticated
    async def post(self):
        body = json.loads(self.request.body)
        notebook = body.get("notebook", "")
        username = body.get("username", "")
        url = body.get("url", "") or "https://ganymede.icos-cp.eu"

        params = urllib.parse.urlencode({
            "idsite": MATOMO_SITE_ID,
            "rec": "1",
            "action_name": f"{username}:{notebook}",
            "url": url,
            "uid": f"{username}:{notebook}",
            "ua": self.request.headers.get("User-Agent", ""),
        })

        try:
            client = AsyncHTTPClient()
            await client.fetch(f"{MATOMO_URL}?{params}", raise_error=False)
        except Exception as e:
            log.warning("Matomo tracking failed: %s", e)

        self.finish(json.dumps({"status": "ok"}))


class FreezeHandler(APIHandler):
    """Snapshot of the session image plus a directory's dependency files."""

    @web.authenticated
    def get(self):
        path = self.get_query_argument("path", default="")
        snapshot = _freeze_snapshot(self, path)

        image = _session_image()
        blocked = _dockerfile_block_reason(
            image, snapshot["conflicts"], snapshot["notebook_installs"]
        )
        dockerfile = None
        written = None
        dockerignore_written = None
        manifest_written = None
        if blocked is None:
            dockerfile = _generate_dockerfile(
                path,
                image,
                snapshot["environment"],
                snapshot["user_installed"],
                snapshot["missing"],
                snapshot["python_version"],
                snapshot["provenance_method"],
            )
            # A GET that writes to disk is not ideal, but freezing has to
            # leave the build context next to the notebooks without a
            # second click. The writes are idempotent: content that
            # already matches is left untouched, and a hand-written
            # Dockerfile or .dockerignore is never replaced.
            context = _write_build_context(
                snapshot["directory"], dockerfile, image, snapshot
            )
            written = context["dockerfile"]
            dockerignore_written = context["dockerignore"]
            manifest_written = context["manifest"]

        self.finish(json.dumps({
            "path": path,
            "image": image,
            "python_version": snapshot["python_version"],
            "provenance_method": snapshot["provenance_method"],
            # Names only. The content of each dependency file is
            # collected for the conflict check and stays on the
            # server; nothing in the browser reads it.
            "requirements": [
                item["name"] for item in snapshot["requirements"]
            ],
            "notebooks": snapshot["notebooks"],
            "environment": snapshot["environment"],
            "user_installed": snapshot["user_installed"],
            "missing": snapshot["missing"],
            "conflicts": snapshot["conflicts"],
            "notebook_installs": snapshot["notebook_installs"],
            "dockerfile": dockerfile,
            "dockerfile_blocked": blocked,
            "dockerfile_written": written,
            "dockerignore_written": dockerignore_written,
            "manifest_written": manifest_written,
            # Whether the frontend may offer the handover package.
            # True only when a generated Dockerfile is actually on
            # disk: the package is built around that file, and a
            # Dockerfile that was generated but never written is no
            # use to whoever has to build it. The bundle endpoint
            # refuses on the same two checks.
            "bundle_available": written in DOCKERFILE_ON_DISK,
        }))


class BundleHandler(APIHandler):
    """Serves a frozen directory as a zip someone else can build and run.

    The freeze leaves a build context beside the notebooks, which is
    enough for whoever is already sitting in front of that directory. A
    tester is not: they get this package and nothing else, so it carries
    the notebooks, their dependency files, the build context and a
    README with the real commands in it.

    A copy is left in the frozen directory as well, so the same package
    can be handed on again later without freezing a second time.
    """

    def finish(self, *args, **kwargs):
        """Finish the response, keeping the Content-Type set in get().

        APIHandler.finish sets "Content-Type: application/json" on every
        response it completes. Newer jupyter_server versions take a
        "set_content_type" keyword to say otherwise and older 2.x ones
        do not, so that one line is skipped rather than argued with, and
        each response below sets its own content type.
        """
        self.update_api_activity()
        return super(APIHandler, self).finish(*args, **kwargs)

    @web.authenticated
    def get(self):
        path = self.get_query_argument("path", default="")

        # The snapshot is collected from the directory itself, so the
        # package is refused for the same reasons a freeze would be.
        snapshot = _freeze_snapshot(self, path)
        directory = snapshot["directory"]

        image = _session_image()
        blocked = _dockerfile_block_reason(
            image, snapshot["conflicts"], snapshot["notebook_installs"]
        )
        if blocked is not None:
            self.set_status(409)
            self.set_header("Content-Type", "application/json")
            self.finish(json.dumps({"status": "blocked", "reason": blocked}))
            return

        dockerfile = _generate_dockerfile(
            path,
            image,
            snapshot["environment"],
            snapshot["user_installed"],
            snapshot["missing"],
            snapshot["python_version"],
            snapshot["provenance_method"],
        )
        # The context is written before the archive is built, and the
        # archive then reads it back, so what the tester unpacks is what
        # the frozen directory holds.
        context = _write_build_context(
            directory, dockerfile, image, snapshot
        )
        if context["dockerfile"] not in DOCKERFILE_ON_DISK:
            # Without a generated Dockerfile on disk the package
            # would carry someone else's Dockerfile, or none at all,
            # while its README tells the tester to build from it.
            self.set_status(409)
            self.set_header("Content-Type", "application/json")
            self.finish(json.dumps({
                "status": "blocked",
                "reason": _dockerfile_write_reason(
                    context["dockerfile"]
                ),
            }))
            return

        name, data = _bundle_archive(directory, snapshot, image)
        saved = _write_bundle(directory, name, data)

        self.set_header("Content-Type", "application/zip")
        self.set_header("Content-Disposition", f'attachment; filename="{name}"')
        if saved:
            # Only set when the copy landed, so the frontend can say
            # "downloaded" rather than "saved beside your notebooks"
            # without having to guess.
            self.set_header("X-Icos-Freeze-Saved", name)
        self.finish(data)


def setup_handlers(web_app):
    base_url = web_app.settings.get("base_url", "/")
    handlers = [
        (url_path_join(base_url, "icos-ext", "track"), TrackHandler),
        (url_path_join(base_url, "icos-ext", "freeze"), FreezeHandler),
        (url_path_join(base_url, "icos-ext", "bundle"), BundleHandler),
    ]
    web_app.add_handlers(".*$", handlers)
